name: flutter_communication
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.3

  # Authentications
  firebase_core: ^1.20.0
  firebase_core_platform_interface: 4.5.1
  firebase_auth: ^3.5.0
  flutter_facebook_auth: ^5.0.7
  google_sign_in: ^5.4.4
  local_auth: ^2.1.3

  #Database Handler
  shared_preferences: ^2.0.15 # Cache Mode
  cloud_firestore: ^3.4.0
  firebase_database: ^9.1.7
  firebase_messaging: ^13.0.4

  #Data equations
  equatable: ^2.0.5

  #Permission controller
  permission_handler: ^10.2.0

  # Dependency Injections
  get_it: ^7.2.0

  # State management
  flutter_bloc: ^8.1.2

  # Toast
  fluttertoast: ^8.1.2

  # SVG Icon loader
  flutter_svg: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/